export const formSchema = [
  {
    name: "id",
    disabled: true,
    type: "text",
    label: "ID",
    errorKey: "",
  },
  {
    name: "userName",
    disabled: false,
    type: "text",
    label: "User Name",
    errorKey: "",
    rules: { required: true },
  },

  {
    name: "email",
    disabled: false,
    type: "text",
    label: "Email",
    rules: { required: true },
  },
  {
    name: "firstName",
    disabled: false,
    type: "text",
    label: "First Name",
    errorKey: "",
    rules: { required: true },
  },
  {
    name: "lastName",
    disabled: false,
    type: "text",
    label: "Last Name",
    errorKey: "",
    rules: { required: true },
  },
  {
    name: "mobile",
    disabled: false,
    type: "text",
    label: "Mobile",
    errorKey: "",
    rules: { required: true },
  },
  {
    name: "roles",
    disabled: false,
    type: "dropdown",
    label: "Roles",
    dropDownOption: [],
    errorKey: "",
    rules: { required: true },
  },
  {
    name: "isActive",
    disabled: false,
    type: "dropdown",
    label: "Is Active Account?",
    dropDownOption: [
      { name: "Yes", value: true },
      { name: "No", value: false },
    ],
    errorKey: "This field cannot be blank.",
    rules: { required: true },
  },
  {
    name: "isDeleted",
    disabled: false,
    type: "dropdown",
    label: "Is Account Deleted ?",
    dropDownOption: [
      { name: "Yes", value: true },
      { name: "No", value: false },
    ],
    errorKey: "This field cannot be blank.",
    rules: { required: true },
  },
  {
    name: "token",
    disabled: true,
    type: "text",
    label: "Token",
    errorKey: "",
  },
  {
    name: "validTill",
    disabled: true,
    type: "text",
    label: "Token Valid Till",
    errorKey: "",
  },
  {
    name: "lastLogin",
    disabled: true,
    type: "text",
    label: "Last Login",
    errorKey: "",
  },
  {
    name: "invalidLogins",
    disabled: true,
    type: "text",
    label: "Login Attempts Left",
    errorKey: "",
  },
  {
    name: "created_at",
    disabled: true,
    type: "text",
    label: "Created At",
    errorKey: "",
  },
  {
    name: "updated_at",
    disabled: true,
    type: "text",
    label: "Updated At",
    errorKey: "",
  },
  {
    name: "createdBy",
    disabled: true,
    type: "text",
    label: "Created By",
    errorKey: "",
  },
];
