import ROUTES from "./routeConstants.js";

export const APP_CONSTANTS = Object.freeze({
  SUPER_ADMIN: {
    SIDEBAR: [
      {
        id: "b5114f33-ddc3-4fcd-9347-91a6cd17f222",
        name: "Product",
        route: `${ROUTES.ADMINISTRATION}/${ROUTES.SUPER_ADMIN.MAIN}/${ROUTES.SUPER_ADMIN.PRODUCT}`,
      },

      {
        id: "ebb6df4a-ce4a-481d-be18-72eaab290ebf",
        name: "Location",
        route: `${ROUTES.ADMINISTRATION}/${ROUTES.SUPER_ADMIN.MAIN}/${ROUTES.SUPER_ADMIN.LOCATION}`,
      },
      {
        id: "1058df14-d076-405f-a63c-fea410942604",
        name: "Master",
        route: `${ROUTES.ADMINISTRATION}/${ROUTES.SUPER_ADMIN.MAIN}/${ROUTES.SUPER_ADMIN.MASTER}`,
      },
    ],
  },
  ADMIN: {
    SIDEBAR: [
      {
        id: "b5114f33-ddc3-4fcd-9347-91a6cd17f222",
        name: "Product",
        route: `${ROUTES.ADMINISTRATION}/${ROUTES.ADMIN.MAIN}/${ROUTES.ADMIN.PRODUCT}`,
      },
    ],
  },
  QUERY_KEYS: {
    GET_LOCATION_QUERY: "GET_LOCATION_QUERY",
    GET_ALL_MASTER: "GET_ALL_MASTER",
    GET_USER_BY_ID: "GET_USER_BY_ID",
    GET_ALL_ROLES: "GET_ALL_ROLES",
    GET_ALL_ENTITIES_LIST: "GET_ALL_ENTITIES_LIST",
    GET_LOGGED_IN_USER_MASTER: "GET_LOGGED_IN_USER_MASTER",
    GET_ENTITY_BY_ID: "GET_ENTITY_BY_ID",
    GET_LOGGED_IN_USER: "GET_LOGGED_IN_USER",
    GET_HSN_BY_CODE_AND_DESCRIPTION: "GET_HSN_BY_CODE_AND_DESCRIPTION",
    GET_ALL_UNITS: "GET_ALL_UNITS",
  },
  GLOBAL_STORE: {
    SET_ROLES: "SET_ROLES",
    SET_ENTITIES: "SET_ENTITIES",
    SET_LOGGEDIN_MASTER_USER: "SET_LOGGEDIN_MASTER_USER",
    SET_LOCATION_LIST: "SET_LOCATION_LIST",
    SET_LOGGED_IN_USER: "SET_LOGGED_IN_USER",
    SET_UNITS: "SET_UNITS",
  },
});
